### ISSUE TITLE
import_gtfs should handle urls without .zip extenstion

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#12]
Currently the vignette isn't working for me because GO Durham is directed to a web page that isn't a zip file in transit feeds.  

I think that this should be handled in import_gtfs to look for a .zip extension first and not and throw up a warning as general way to handle these warnings.

**Comment by dantonnoriega** [comment]
You're correct that Go Transit changed their API link to https://gotransitnc.org/developer-resources/gtfs which is not a direct feed.

However, I still prefer the warning as opposed to checking for .zip because I have found compressed files that don't end in zip that successfully unpack and load (can't find an example). Hence, I prefer the flexibility, the throwing of warning, and the return of a NULL object.
