### ISSUE TITLE
Update for newer version of R

### ISSUE THREAD

**Issue by JFCantinMTL** [ropenscilabs/gtfsr#42]
Hello,

I'm new to R. Tried to install this package and got this message :"package ‘gtfsr’ is not available (for R version 3.4.1)

Looking forward to work with this package

**Comment by dantonnoriega** [comment]
Could you write the code you used to try and install the package?

My guess is that you ran `install.package("gtfsr")`. This won't work because the package is not on CRAN.

You must install using devtools: `devtools::install_github('ropensci/gtfsr')`.

Hope that helps! I just tested an install and it worked on my end. I'm also using R 3.4.1.

**Comment by JFCantinMTL** [comment]
Your're right. Thanks !
